---
language: emacs-lisp
sudo: false
cache: apt

env:
  - EVM_EMACS=emacs-27.1-travis-linux-xenial
  - EVM_EMACS=emacs-26.3-travis-linux-xenial

before_install:
  - git clone https://github.com/rejeep/evm.git ~/.evm
  - export PATH="~/.evm/bin:$PATH"
  - evm config path /tmp

install:
  - evm install $EVM_EMACS --use --skip
  - ln -s "$(pwd)/.emacs.d" ~/.emacs.d
  - emacs --script .emacs.d/test/lisp/install.el
  - echo "base-config" > .emacs.d/lisp/user/default-username

before_script:
  - emacs --version

script:
  - emacs --script .emacs.d/test/lisp/run-tests.el
  - emacs --script .emacs.d/init.el
