name: Emacs Tests
on:
  - push

jobs:
  test-emacs:
    name: Install Emacs and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Download Emacs 26.3 sources
        run: wget -O /tmp/emacs-26.3.tar.xz https://ftp.gnu.org/pub/gnu/emacs/emacs-26.3.tar.xz

      - name: Extract Emacs 26.3 sources
        run: tar -C /tmp -xf /tmp/emacs-26.3.tar.xz

      - name: Compile Emacs 26.3
        run: |
          cd /tmp/emacs-26.3
          sudo apt install libgnutls28-dev
          ./configure --with-x-toolkit=no --with-xpm=no --with-gif=no
          make
          sudo make install

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Symlink our .emacs.d to ~
        run: |
          ln -sv "$(pwd)/.emacs.d" ~/.emacs.d

      - name: Run setup
        run: |
          emacs --script .emacs.d/test/lisp/install.el
          echo "base-config" > .emacs.d/lisp/user/default-username

      - name: Run the tests
        run: |
          emacs --script .emacs.d/test/lisp/run-tests.el
          emacs --script .emacs.d/init.el
