name: Emacs Configuration Tests
on:
  - push

jobs:
  test-emacs:
    name: Run Emacs tests
    runs-on: ubuntu-latest
    steps:
      - name: Install EVM
        run: |
          git clone https://github.com/rejeep/evm.git ~/.evm
          ~/.evm/bin/evm list

      - name: Install Emacs 26.3
        run: |
          sudo ~/.evm/bin/evm install emacs-26.3-travis --use --skip
          ~/.evm/bin/emacs --version

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Symlink our .emacs.d to ~
        run: |
          ln -sv "$(pwd)/.emacs.d" ~/.emacs.d

      - name: Run setup
        run: |
          ~/.evm/bin/emacs --script .emacs.d/test/lisp/install.el
          echo "base-config" > .emacs.d/lisp/user/default-username

      - name: Run the tests
        run: |
          ~/.evm/bin/emacs --script .emacs.d/test/lisp/run-tests.el
          ~/.evm/bin/emacs --script .emacs.d/init.el
